//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEProject1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgeState
    {
        public string Id { get; set; }
        public string Age { get; set; }
        public string Sex { get; set; }
        public Nullable<decimal> NSW { get; set; }
        public Nullable<decimal> VIC { get; set; }
        public Nullable<decimal> QLD { get; set; }
        public Nullable<decimal> SA { get; set; }
        public Nullable<decimal> WA { get; set; }
        public Nullable<decimal> TAS { get; set; }
        public Nullable<decimal> NT { get; set; }
        public Nullable<decimal> ACT { get; set; }
    }
}
