//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEProject1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public int Id { get; set; }
        public string ContentName { get; set; }
        public string ImageName { get; set; }
        public Nullable<decimal> Popularity { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string Comment { get; set; }
    
        public virtual Field Field { get; set; }
    }
}
