//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEProject1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPlace
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Adress { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public Nullable<decimal> longitude { get; set; }
        public Nullable<int> Total_rating_people { get; set; }
        public string Photo_reference { get; set; }
        public Nullable<int> Field_id { get; set; }
    
        public virtual Field Field { get; set; }
    }
}
