//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEProject1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SportType
    {
        public string Id { get; set; }
        public string Sport_Type { get; set; }
        public Nullable<decimal> Males { get; set; }
        public Nullable<decimal> Females { get; set; }
        public Nullable<decimal> Total { get; set; }
    }
}
